r"""Give the supplement the paper's bibliography without a second copy to keep.

The supplement is a separate document and needs its own thebibliography block,
but a hand-kept copy of a hundred entries drifts the first time a reference is
corrected in one file and not the other.  So the block is not kept: it is cut
out of the manuscript at build time and written to paper/_suppbib.tex, which
the supplement inputs.  The generated file is not edited and not audited; its
only source is the manuscript.
"""
import io
import os

BS = chr(92)
HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.join(os.path.dirname(HERE), "paper")

s = io.open(os.path.join(PAPER, "mssp.tex"), encoding="utf-8").read()
a = s.find(BS + "begin{thebibliography}")
b = s.find(BS + "end{thebibliography}")
assert a > 0 and b > a, "the manuscript has no bibliography block"
block = s[a:b] + BS + "end{thebibliography}" + "\n"

out = os.path.join(PAPER, "_suppbib.tex")
io.open(out, "w", encoding="utf-8", newline="\n").write(
    "% generated by work/make_supplement_bib.py -- do not edit\n" + block)
print("  wrote %s (%d bibitems)" % (out, block.count(BS + "bibitem")))
